### ISSUE TITLE
KoGPT2 사라짐

### ISSUE THREAD

**Issue by predict-woo** [haven-jeon/KoGPT2-chatbot#10]
KoGPT2가 최근에 repository가 삭제되었습니다

**Comment by haven-jeon** [comment]
모델에 이슈가 있어서 내린 상황이고 곧 올릴 예정입니다.

**Comment by eunjiinkim** [comment]
안녕하세요, 현재 kogpt2를 활용하여 fine-tuning하는 연구를 진행해보고자 하는데 언제쯤 업데이트 예정인지 알 수 있을까요? 감사합니다 :)

**Comment by haven-jeon** [comment]
새로 학습을 진행했구요. 현재 성능 평가를 진행하고 있으며 늦어도 차주에는 오픈을 할 수 있을거 같습니다.
비슷한 파라메터에 기존 모델보다 더 성능은 좋아졌다는 것을 미리 알려드립니다. ^^ 
기다려 주셔서 감사합니다.

**Comment by haven-jeon** [comment]
https://github.com/SKT-AI/KoGPT2 오늘 공개 되었습니다.

감사합니다.  해당 이슈는 클로즈 하겠습니다.
