### ISSUE TITLE
Memory Leak Issue

### ISSUE THREAD

**Issue by imsoncod** [haven-jeon/KoGPT2-chatbot#11]
https://github.com/haven-jeon/KoGPT2-chatbot/blob/9faa8aae64498bd06807914b4c67eb30c14c7465/train.py#L273-L281

해당코드에서 Memory Leak 현상이 발생합니다. input_ids, pred, gen 객체가 계속해서 메모리를 쌓고 있습니다.
del로 명시적 제거를 하거나 gc.collect()로 회수를 해도 메모리가 반환되지 않습니다.

혹시 원인을 알 수 있을까요?

**Comment by haven-jeon** [comment]
CPU 모드로 진행하면 어떤가요?

**Comment by imsoncod** [comment]
@haven-jeon GPU가 탑재되어 있지 않은 t3인스턴스에서 CPU로 테스트했습니다 :)
GPU로 진행시에도 GPU메모리가 아닌 시스템메모리에서 Leak현상이 발생합니다.

**Comment by haven-jeon** [comment]
제 쪽에서 해당 이슈를 재현하기 어렵습니다. 어떤 환경에서 어떠한 상황에서 재현할 수 있는지 알려주시면 확인하는데 도움이 될거 같습니다.

**Comment by imsoncod** [comment]
@haven-jeon 올려주신 Colab(Mxnet)으로 챗봇과 계속 대화를 하게되면 RAM이 계속 쌓이게 됩니다. 이를 EC2와 같은 다른 서버에서 실행해도 같은 현상입니다. 프로세스 자체를 종료해야만 메모리가 반환됩니다.

1. 코드에서 메모리가 할당되는 부분은 3개 였습니다.
```python
input_ids = mx.nd.array([vocab[U_TKN]] + vocab[q_tok] + 
                         vocab[EOS, SENT] + vocab[sent_tokens] + 
                         vocab[EOS, S_TKN] + 
                         vocab[a_tok]).expand_dims(axis=0) <-------- 이곳
 pred = kogptqa(input_ids.as_in_context(ctx))  <-------- 이곳
 gen = vocab.to_tokens( 
     mx.nd.argmax( 
         pred, 
         axis=-1).squeeze().astype('int').asnumpy().tolist())[-1]  <-------- 이곳
```

2. gc가 추적하는 객체들을 출력해보았는데 추론을 할 때마다 객체들이 쌓이고 있었습니다. 
반복적으로 쌓이고 있는 객체는 아래와 같았습니다.(다른 것일수도 있습니다)
`<mxnet.base.c_void_p_Array_1 object at 0x7ffa4c347680>
{140712997058176: <mxnet.base.c_void_p_Array_1 object at 0x7ffa4c347680>}`

**Comment by haven-jeon** [comment]
v2로 버전업 되면서 MXNet 코드가 모두 제거 되었습니다. 다시 확인해보시고 문제가 여전하시다면 이슈 다시 올려주시면 감사하겠습니다.
