### ISSUE TITLE
KoGPT2 install 질문있습니다.

### ISSUE THREAD

**Issue by lee-jeongha** [haven-jeon/KoGPT2-chatbot#12]
코드 따라하면서 조금씩 공부중입니다.
이번에 KoGPT2가 v2로 재공개되어서 다시 실습해보는 중인데요.

`!pip install git+https://github.com/SKT-AI/KoGPT2#egg=kogpt2` 에서 다음과 같은 에러가 납니다.

`ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

해당 에러 메시지를 구글링해봐도 며칠째 해결이 안되어서 질문드립니다.

**Comment by haven-jeon** [comment]
v2.0 올라가면서 설치 없이 바로 모델로딩이 되게 되었습니다.

https://github.com/SKT-AI/KoGPT2/blob/master/README.md 

참고하세요.

**Comment by lee-jeongha** [comment]
네 감사합니다! KoGPT2 버전 올라가면서 해당 코드도 수정된 걸 확인 못했네요...

새로 올라온 코드로 다시 시도해보는 중인데, 다음과 같이 에러가 납니다.
![image](https://user-images.githubusercontent.com/81732746/117557396-6f6a4b80-b0ad-11eb-9d6a-f450cffded23.png)

현재 코랩 환경에서 실습진행하고 있습니다.
해당 에러 해결에 조언 부탁드립니다 :)

**Comment by haven-jeon** [comment]
이 이슈는 얼마전에 업데이트된 pytorch_lightning 이슈입니다. requirements.txt를 추가했으니 문제 없으실 겁니다. 

914240c0acc46b7e9f62302d1304711dd650e5a8

**Comment by lee-jeongha** [comment]
네! 정말 감사합니다 :)
