### ISSUE TITLE
패키지 종속성 파일 요청

### ISSUE THREAD

**Issue by minibox24** [haven-jeon/KoGPT2-chatbot#13]
이 프로젝트에서 사용되는 패키지 종속성 파일(requirements.txt)을 같이 커밋해주시면 좋을 것 같습니다.

(현재 #9 또는 README.md에 적혀있는 패키지 버전을 사용해도 문제가 생깁니다.)

**Comment by haven-jeon** [comment]
914240c0acc46b7e9f62302d1304711dd650e5a8 했습니다.  문제가 생긴건 얼마전에 업데이트된 pytorch lightning 버전 때문이군요..
