### ISSUE TITLE
KoGPT2 model ckp관련 질의사항입니다.

### ISSUE THREAD

**Issue by Ethan0625** [haven-jeon/KoGPT2-chatbot#14]
모델 학습을 시키고 나면 model_chp폴더가 생성되고 model_-last.ckpt라는 파일이 생성됩니다.

그렇다면 혹시 모델을 다시 학습시킬 때 해당 파라미터는 공유가 되는건가요?

**Comment by haven-jeon** [comment]
코드 전체가 PyTorch Lightning 체계로 만들어져 있어서  해당 체크 포인트를 아래와 같이 로딩 후 이어서 학습하시면 됩니다. 

https://pytorch-lightning.readthedocs.io/en/stable/common/weights_loading.html#checkpoint-loading

**Comment by Ethan0625** [comment]
좋은답변 감사합니다~!
