### ISSUE TITLE
train_torch.py파일 관련 질의사항

### ISSUE THREAD

**Issue by Ethan0625** [haven-jeon/KoGPT2-chatbot#15]
train_torch.py파일의 line 202에 적혀있는 q_tok = tok.tokenize(q)에서 q_tok은 다른 부분에서 사용되지 않는 것 같은데 혹시 사용되는 곳이 따로 정해져있나요??

**Comment by haven-jeon** [comment]
네.. 말씀하신 내용이 맞습니다. 필요 없는 코드여서 제거해야 겠네요. 

efe2047ebf9f24e2439a69bf45d14bdf13fcb896

**Comment by Ethan0625** [comment]
넵 확인 감사합니다~!
