### ISSUE TITLE
!CUDA_VISIBLE_DEVICES=0 python train_torch.py --train --gpus 1 --max_epochs 2 shape 오류 

### ISSUE THREAD

**Issue by Parkjiwonha** [haven-jeon/KoGPT2-chatbot#8]
안녕하세요 올려주신 코드로 파인튜닝 하는 과정에서 
File "train_torch.py", line 161, in training_step
    mask_3d = mask.unsqueeze(dim=2).repeat_interleave(repeats=out.shape[2], dim=2)
AttributeError: 'str' object has no attribute 'shape'
오류가 나는데 해결책을 찾지 못해서 이슈 남깁니다ㅠㅠ 
감사합니다!

**Comment by HaloKim** [comment]
해결하셨나요 ?
같은 오류를 갖고있습니다..

- 해결법
- https://github.com/haven-jeon/KoGPT2-chatbot/issues/9#issue-772704923
